Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      DigAsicStrmRegisters0:
        enable: True
        asicDataReq: 3071
        #DisableLane: 0x0
        #DisableLane: 0x0 # carrier 2
        DisableLane: 0x100 # carrier 3
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters1:
        enable: True
        asicDataReq: 3071
        #DisableLane: 0x9 # carrier 2
        DisableLane: 0x1 # carrier 3
        #DisableLane: 0x0
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters2:
        enable: True
        asicDataReq: 3071
        #DisableLane: 0xc11110 # carrier 2
        DisableLane: 0xc90000 # carrier 3
        #DisableLane: 0xc0
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters3:
        enable: True
        asicDataReq: 3071
        #DisableLane: 0x1000 # carrier 2
        #DisableLane: 0x0 # carrier 3
        DisableLane: 0x010000
        EnumerateDisLane: 0xffffff
