Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      DigAsicStrmRegisters0:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x0
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters1:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x9
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters2:
        enable: True
        asicDataReq: 3071
        DisableLane: 0xc11110
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters3:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x1000
        EnumerateDisLane: 0xffffff
