Root:
  enable: True
  ForceWrite: False
  App:
    enable: True  
    SspMonGrp[0]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x2
      UsrDlyCfg[1]: 0x10
      UsrDlyCfg[2]: 0x156
      UsrDlyCfg[3]: 0xd8
      UsrDlyCfg[4]: 0x11
      UsrDlyCfg[5]: 0xa2
      UsrDlyCfg[6]: 0x119
      UsrDlyCfg[7]: 0x4c
      UsrDlyCfg[8]: 0x165
      UsrDlyCfg[9]: 0x9f
      UsrDlyCfg[10]: 0x156
      UsrDlyCfg[11]: 0xaf
      UsrDlyCfg[12]: 0x195
      UsrDlyCfg[13]: 0xc4
      UsrDlyCfg[14]: 0x129
      UsrDlyCfg[15]: 0x5d
      UsrDlyCfg[16]: 0x12f
      UsrDlyCfg[17]: 0x4e
      UsrDlyCfg[18]: 0x114
      UsrDlyCfg[19]: 0x94
      UsrDlyCfg[20]: 0x106
      UsrDlyCfg[21]: 0x74
      UsrDlyCfg[22]: 0x17
      UsrDlyCfg[23]: 0x61
    SspMonGrp[1]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0xff
      UsrDlyCfg[1]: 0xe1
      UsrDlyCfg[2]: 0x2e
      UsrDlyCfg[3]: 0xff
      UsrDlyCfg[4]: 0x2c
      UsrDlyCfg[5]: 0xcb
      UsrDlyCfg[6]: 0x144
      UsrDlyCfg[7]: 0x89
      UsrDlyCfg[8]: 0x17f
      UsrDlyCfg[9]: 0xdd
      UsrDlyCfg[10]: 0x2d
      UsrDlyCfg[11]: 0xe6
      UsrDlyCfg[12]: 0x26
      UsrDlyCfg[13]: 0xf8
      UsrDlyCfg[14]: 0x145
      UsrDlyCfg[15]: 0x7b
      UsrDlyCfg[16]: 0x6c
      UsrDlyCfg[17]: 0x60
      UsrDlyCfg[18]: 0x11d
      UsrDlyCfg[19]: 0xb4
      UsrDlyCfg[20]: 0x131
      UsrDlyCfg[21]: 0x85
      UsrDlyCfg[22]: 0x34
      UsrDlyCfg[23]: 0x80
    SspMonGrp[2]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x6b
      UsrDlyCfg[1]: 0x12b
      UsrDlyCfg[2]: 0xa2
      UsrDlyCfg[3]: 0xff
      UsrDlyCfg[4]: 0x94
      UsrDlyCfg[5]: 0x112
      UsrDlyCfg[6]: 0x3b
      UsrDlyCfg[7]: 0xff
      UsrDlyCfg[8]: 0x69
      UsrDlyCfg[9]: 0x12e
      UsrDlyCfg[10]: 0xc8
      UsrDlyCfg[11]: 0x108
      UsrDlyCfg[12]: 0xa9
      UsrDlyCfg[13]: 0x165
      UsrDlyCfg[14]: 0x7f
      UsrDlyCfg[15]: 0xff
      UsrDlyCfg[16]: 0xff
      UsrDlyCfg[17]: 0xff
      UsrDlyCfg[18]: 0x50
      UsrDlyCfg[19]: 0xff
      UsrDlyCfg[20]: 0x8d
      UsrDlyCfg[21]: 0x2f
      UsrDlyCfg[22]: 0xff
      UsrDlyCfg[23]: 0xff
    SspMonGrp[3]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x77
      UsrDlyCfg[1]: 0x10f
      UsrDlyCfg[2]: 0x8c
      UsrDlyCfg[3]: 0xff
      UsrDlyCfg[4]: 0x98
      UsrDlyCfg[5]: 0x1d
      UsrDlyCfg[6]: 0x33
      UsrDlyCfg[7]: 0xe7
      UsrDlyCfg[8]: 0x45
      UsrDlyCfg[9]: 0x1
      UsrDlyCfg[10]: 0x8c
      UsrDlyCfg[11]: 0xff
      UsrDlyCfg[12]: 0x93
      UsrDlyCfg[13]: 0x149
      UsrDlyCfg[14]: 0x5f
      UsrDlyCfg[15]: 0xea
      UsrDlyCfg[16]: 0xd
      UsrDlyCfg[17]: 0xec
      UsrDlyCfg[18]: 0x41
      UsrDlyCfg[19]: 0xff
      UsrDlyCfg[20]: 0x44
      UsrDlyCfg[21]: 0xfc
      UsrDlyCfg[22]: 0x19
      UsrDlyCfg[23]: 0xf2