Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      DigAsicStrmRegisters0:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x500003
        EnumerateDisLane: 0x0
        fillOnFailEn: 0x1
        fillOnFailTimeout: 4
        fillOnFailTimeoutOffset: 620        
      DigAsicStrmRegisters1:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x510001
        EnumerateDisLane: 0x0
        fillOnFailEn: 0x1
        fillOnFailTimeout: 4
        fillOnFailTimeoutOffset: 620        
      DigAsicStrmRegisters2:
        enable: True
        asicDataReq: 3071
        DisableLane: 0xe90000
        EnumerateDisLane: 0x0
        fillOnFailEn: 0x1
        fillOnFailTimeout: 4
        fillOnFailTimeoutOffset: 620        
      DigAsicStrmRegisters3:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x410220
        EnumerateDisLane: 0x0
        fillOnFailEn: 0x1
        fillOnFailTimeout: 4
        fillOnFailTimeoutOffset: 620        