ePixHr10kT:
  enable: True
  EpixHR:
    enable: True
    RegisterControl:
      enable: True
      Version: 0x1
      GlblRstPolarity: True
      AcqPolarity: False
      AcqDelay1: 200
      AcqWidth1: 100
      AcqDelay2: 0
      AcqWidth2: 0
      TPulsePolarity: False
      TPulseDelay: 0
      TPulseWidth: 0
      R0Polarity: False
      R0Delay: 100
      R0Width: 300
      PPbePolarity: False
      PPbeDelay: 0
      PPbeWidth: 0
      PpmatPolarity: False
      PpmatDelay: 0
      PpmatWidth: 0
      SyncPolarity: False
      SyncDelay: 20000
      SyncWidth: 100
      SaciSyncPolarity: False
      SaciSyncDelay: 0
      SaciSyncWidth: 0
      SR0Polarity: False
      SR0Delay1: 500
      SR0Width1: 19000
      Vid: 0
      ResetCounters: False
      AsicPwrEnable: False
      AsicPwrManual: False
      AsicPwrManualDig: False
      AsicPwrManualAna: False
      AsicPwrManualIo: False
      AsicPwrManualFpga: False
      DebugSel1: 17
      DebugSel2: 17
      AdcClkHalfT: 1
      StartupReq: True
      ClkEn: True