ePixHr10kT2M:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      TriggerRegisters:
        enable: True
        RunTriggerEnable: False
        TimingRunTriggerEnable: False
        RunTriggerDelay: 0
        DaqTriggerEnable: False
        TimingDaqTriggerEnable: False
        DaqTriggerDelay: 0
        AutoRunEn: False
        AutoDaqEn: False
        AutoTrigPeriod: 156250000
        PgpTrigEn: False