Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      DigAsicStrmRegisters0:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x0
        EnumerateDisLane: 0x0
        FillOnFailEn: 0x0
        SroToSofTimeout: 270
        DataTimeout: 3  
      DigAsicStrmRegisters1:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x0
        EnumerateDisLane: 0x0
        FillOnFailEn: 0x0
        SroToSofTimeout: 270
        DataTimeout: 3     
      DigAsicStrmRegisters2:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x0
        EnumerateDisLane: 0x0
        FillOnFailEn: 0x0
        SroToSofTimeout: 270
        DataTimeout: 3      
      DigAsicStrmRegisters3:
        enable: True
        asicDataReq: 3071
        DisableLane: 0x0
        EnumerateDisLane: 0x0
        FillOnFailEn: 0x0
        SroToSofTimeout: 270
        DataTimeout: 3  
