Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      BatcherEventBuilder0:
        enable: True
        Bypass: 0x1
        Timeout: 0x0
        Blowoff: False
      BatcherEventBuilder1:
        enable: True
        Bypass: 0x1
        Timeout: 0x0
        Blowoff: False
      BatcherEventBuilder2:
        enable: True
        Bypass: 0x1
        Timeout: 0x0
        Blowoff: False
      BatcherEventBuilder3:
        enable: True
        Bypass: 0x1
        Timeout: 0x0
        Blowoff: False