Root:
  enable: True
  ForceWrite: False
  App:
    enable: True  
    SspMonGrp[0]:
      enable: True
      EnUsrDlyCfg: 0x0
    SspMonGrp[1]:
      enable: True
      EnUsrDlyCfg: 0x0
    SspMonGrp[2]:
      enable: True
      EnUsrDlyCfg: 0x0
    SspMonGrp[3]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x77
      UsrDlyCfg[1]: 0x121
      UsrDlyCfg[2]: 0x99
      UsrDlyCfg[3]: 0x187
      UsrDlyCfg[4]: 0x88
      UsrDlyCfg[5]: 0xff
      UsrDlyCfg[6]: 0x33
      UsrDlyCfg[7]: 0xdd
      UsrDlyCfg[8]: 0x22
      UsrDlyCfg[9]: 0xff
      UsrDlyCfg[10]: 0x88
      UsrDlyCfg[11]: 0xff
      UsrDlyCfg[12]: 0x66
      UsrDlyCfg[13]: 0x132
      UsrDlyCfg[14]: 0x44
      UsrDlyCfg[15]: 0xdd
      UsrDlyCfg[16]: 0x198
      UsrDlyCfg[17]: 0xbb
      UsrDlyCfg[18]: 0x44
      UsrDlyCfg[19]: 0xff
      UsrDlyCfg[20]: 0x11
      UsrDlyCfg[21]: 0xdd
      UsrDlyCfg[22]: 0x0
      UsrDlyCfg[23]: 0xee      

   