Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      DigAsicStrmRegisters0:
        enable: True
        asicDataReq: 3071
        DisableLane: 0xffffff
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters1:
        enable: True
        asicDataReq: 3071
        DisableLane: 0xffffff
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters2:
        enable: True
        asicDataReq: 3071
        DisableLane: 0xffffff
        EnumerateDisLane: 0xffffff
      DigAsicStrmRegisters3:
        enable: True
        asicDataReq: 3071
        DisableLane: 0xffffff
        EnumerateDisLane: 0xffffff
