Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    Mv2Asic[1]:
      enable: True
      shvc_DAC: 30
      fastPP_enable: False
      PulserSync: False
      Pll_RO_Reset: True
      Pll_Itune: 0x2
      Pll_KVCO: 0x4
      Pll_filter1LSB: 0x1
      Pll_filter1MSB: 0x1
      Pulser: 0x200
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x7
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      RefGenB: 0x1
      Dm1En: True
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef_DAC: 0x10
      VRefLow: 0x3
      trbit: False
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      Balcony_clk: 0x0
      PpOcbS2d: True
      Ocb: 0x3
      Monost: 0x3
      mTest: False
      Preamp: 0x4
      S2D_1_b: 0x0
      Vld1_b: 0x1
      CompTH_DAC: 0x2a
      TC: 0x0
      S2d: 0x3
      S2dDacBias: 0x3
      Tsd_Tser: 0x0
      Tps_DAC: 0x16
      PLL_RO_filter2: 0x2
      PLL_RO_divider: 0x0
      TestBe: False
      DigRO_disable: False
      DelExec: False
      DelCCKReg: False
      RO_rst_en: True
      SlvdsBit: True
      FE_Autogain: True
      FE_Lowgain: False
      #RowStartAddr: 0x0
      #RowStopAddr: 0x91
      #ColStartAddr: 0x0
      #ColStopAddr: 0x2f
      DCycle_DAC: 0x0
      DCycle_en: False
      DCycle_bypass: False
      Debug_bit: 0x3
      OSRsel: False
      SecondOrder: False
      DHg: True
      RefGenC: 0x1
      dbus_del_sel: False
      SDclk_b: 0x0
      SDrst_b: 0x8
      Filter_DAC: 0x26
      Ref_gen_d: 0x3
      CompEn: 0x7
      Pixel_CB: 0x4
      InjEn_ePixM: False
      ClkInj_ePixM: False
      rowCK2matrix_delay: 0x4
      RefinN: 0x0
      RefinCompN: 0x3
      RefinP: 0x0
      ro_mode_i: 0x0
      SDclk1_b: 0x0
      SDrst1_b: 0x8
      SDclk2_b: 0x0
      SDrst2_b: 0x8
      SDclk3_b: 0x0
      SDrst3_b: 0x8
      CompTH_ePixM: 0x0
      Precharge_DAC_ePixM: 45
      FE_CLK_dly: 0x4
      FE_CLK_cnt_en: True
      FE_ACQ2GR_en: True
      FE_sync2GR_en: False
      FE_ACQ2InjEn: False
      # To disable banks
      #DigRO_disable2: 0xe
      pipoclk_delay_row0: 15
      pipoclk_delay_row1: 8
      pipoclk_delay_row2: 8
      pipoclk_delay_row3: 8
