Root:
  enable: True
  ForceWrite: False
  App:
    enable: True  
    SspMonGrp[0]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x0
      UsrDlyCfg[1]: 0x7f
      UsrDlyCfg[2]: 0x11c
      UsrDlyCfg[3]: 0x7f
      UsrDlyCfg[4]: 0x1e0
      UsrDlyCfg[5]: 0x7f
      UsrDlyCfg[6]: 0x8a
      UsrDlyCfg[7]: 0x5e
      UsrDlyCfg[8]: 0x143
      UsrDlyCfg[9]: 0x7f
      UsrDlyCfg[10]: 0x122
      UsrDlyCfg[11]: 0x7f
      UsrDlyCfg[12]: 0x1ff
      UsrDlyCfg[13]: 0x7f
      UsrDlyCfg[14]: 0xa4
      UsrDlyCfg[15]: 0x63
      UsrDlyCfg[16]: 0xea
      UsrDlyCfg[17]: 0x7f
      UsrDlyCfg[18]: 0x7f
      UsrDlyCfg[19]: 0x7f
      UsrDlyCfg[20]: 0x1e0
      UsrDlyCfg[21]: 0x7f
      UsrDlyCfg[22]: 0x131
      UsrDlyCfg[23]: 0x67      
    SspMonGrp[1]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x90
      UsrDlyCfg[1]: 0x87
      UsrDlyCfg[2]: 0x70
      UsrDlyCfg[3]: 0xa2
      UsrDlyCfg[4]: 0x7f
      UsrDlyCfg[5]: 0x1ff
      UsrDlyCfg[6]: 0x75
      UsrDlyCfg[7]: 0x7f
      UsrDlyCfg[8]: 0x7f
      UsrDlyCfg[9]: 0x133
      UsrDlyCfg[10]: 0x7f
      UsrDlyCfg[11]: 0x87
      UsrDlyCfg[12]: 0x7f
      UsrDlyCfg[13]: 0x1ff
      UsrDlyCfg[14]: 0x7f
      UsrDlyCfg[15]: 0x7f
      UsrDlyCfg[16]: 0x7f
      UsrDlyCfg[17]: 0x1ff
      UsrDlyCfg[18]: 0x7f
      UsrDlyCfg[19]: 0x82
      UsrDlyCfg[20]: 0x7f
      UsrDlyCfg[21]: 0x1ff
      UsrDlyCfg[22]: 0x7f
      UsrDlyCfg[23]: 0x7f      
    SspMonGrp[2]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x7f
      UsrDlyCfg[1]: 0x4a
      UsrDlyCfg[2]: 0x7f
      UsrDlyCfg[3]: 0x118
      UsrDlyCfg[4]: 0xd8
      UsrDlyCfg[5]: 0x3f
      UsrDlyCfg[6]: 0x7f
      UsrDlyCfg[7]: 0x7f
      UsrDlyCfg[8]: 0x7f
      UsrDlyCfg[9]: 0x15d
      UsrDlyCfg[10]: 0x7f
      UsrDlyCfg[11]: 0xf3
      UsrDlyCfg[12]: 0xc2
      UsrDlyCfg[13]: 0x4b
      UsrDlyCfg[14]: 0x7f
      UsrDlyCfg[15]: 0x7f
      UsrDlyCfg[16]: 0xc1
      UsrDlyCfg[17]: 0x107
      UsrDlyCfg[18]: 0x7f
      UsrDlyCfg[19]: 0xe4
      UsrDlyCfg[20]: 0x7f
      UsrDlyCfg[21]: 0x144
      UsrDlyCfg[22]: 0x4a
      UsrDlyCfg[23]: 0x7f      
    SspMonGrp[3]:
      enable: True
      EnUsrDlyCfg: 0x1
      UsrDlyCfg[0]: 0x77
      UsrDlyCfg[1]: 0x121
      UsrDlyCfg[2]: 0x99
      UsrDlyCfg[3]: 0x187
      UsrDlyCfg[4]: 0x88
      UsrDlyCfg[5]: 0xff
      UsrDlyCfg[6]: 0x33
      UsrDlyCfg[7]: 0xdd
      UsrDlyCfg[8]: 0x22
      UsrDlyCfg[9]: 0xff
      UsrDlyCfg[10]: 0x88
      UsrDlyCfg[11]: 0xff
      UsrDlyCfg[12]: 0x66
      UsrDlyCfg[13]: 0x132
      UsrDlyCfg[14]: 0x44
      UsrDlyCfg[15]: 0xdd
      UsrDlyCfg[16]: 0x198
      UsrDlyCfg[17]: 0xbb
      UsrDlyCfg[18]: 0x44
      UsrDlyCfg[19]: 0xff
      UsrDlyCfg[20]: 0x11
      UsrDlyCfg[21]: 0xdd
      UsrDlyCfg[22]: 0x0
      UsrDlyCfg[23]: 0xee      

   