Root:
  enable: True
  ForceWrite: False
  App:
    enable: True
    AsicTop:
      enable: True
      RegisterControlDualClock:
        enable: True
        GlblRstPolarityN: True
        ClkSyncEn: True
        RoLogicRstN: True
        SyncPolarity: False
        SyncDelay: 40000
        SyncWidth: 100
        SR0Polarity: False
        SR0Delay1: 500
        SR0Width1: 38000
        ePixAdcSHPeriod: 160
        ePixAdcSHOffset: 80
        AcqPolarity: False
        AcqDelay1: 200
        AcqWidth1: 100
        AcqDelay2: 0
        AcqWidth2: 0
        R0Polarity: False
        R0Delay: 100
        R0Width: 300
        PPbePolarity: False
        PPbeDelay: 0
        PPbeWidth: 0
        PpmatPolarity: False
        PpmatDelay: 0
        PpmatWidth: 0
        SaciSyncPolarity: False
        SaciSyncDelay: 0
        SaciSyncWidth: 0
        ResetCounters: False
        AsicPwrEnable: False
        AsicPwrManual: False
        AsicPwrManualDig: False
        AsicPwrManualAna: False
        AsicPwrManualIo: False
        AsicPwrManualFpga: False
        DebugSel0: AsicDM(0)
        DebugSel1: AsicDM(1)
        StartupReq: True