Root:
  enable: True
  ForceWrite: False
  App:
    enable: True  
    SspMonGrp[0]:
      enable: True
      EnUsrDlyCfg: 0x0
    SspMonGrp[1]:
      enable: True
      EnUsrDlyCfg: 0x0
    SspMonGrp[2]:
      enable: True
      EnUsrDlyCfg: 0x0
    SspMonGrp[3]:
      enable: True
      EnUsrDlyCfg: 0x0
   