
# The following environment variables are required for this process:
# secrets.GH_TOKEN

name: ePix 320k M Documentation
on: [push]

jobs:

  test_and_document:
    name: Test And Generate Documentation
    runs-on: ubuntu-20.04
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Branch name
        run:  echo running on branch ${GITHUB_REF##*/}


      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r pip_requirements.txt
          
      - name: Generate Documentation
        run: |
          cd docs
          make html

      - name: Deploy Documentation
        if: startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/build/html
